### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by wasi-master** [noigamegun/AutoPiano#1]
please provide the actual autohotkey script alongside the exe file (to which, I may add, shouldn't even be a part of the code and should be releases as releases on github). GitHub is a place to mainly host source code, not host exe files. You can host them, but please provide the source code for transparency

**Comment by GamuGamiChan** [comment]
Ok I’m busy right now maybe later

**Comment by wasi-master** [comment]
@noigamegun No worries buddy. Do it (or don't) whenever you want, I don’t really care. Just wanted to let you know :)

**Comment by GamuGamiChan** [comment]
Done that what you like?

**Comment by wasi-master** [comment]
@noigamegun you should also change the download link to https://github.com/noigamegun/AutoPiano/releases/download/v.1.0.0/AutoPiano.exe

**Comment by GamuGamiChan** [comment]
Done?

**Comment by wasi-master** [comment]
@noigamegun done. You can close this issue if you want :)
